# -*- coding: utf-8 -*-
import io, os

# 174 个 Fork 特有键的中文翻译（保留 {TAG} 占位符）
TRANS = {
"10_LAST_STAND_TOOLTIP": "获得10个“最后一关”奖杯即可解锁",
"ADVICE_BOMB_ALL_TOGETHER": "炸弹类植物数量有限。",
"ADVICE_HEAT_WAVE": "拖动植物来抵挡僵尸！",
"ALREADY_UNLOCKED_DIALOG_BODY": "你已解锁全部游戏内容。",
"ALREADY_UNLOCKED_DIALOG_HEADER": "已解锁！",
"BACK": "返回",
"BACKUP_DANCER_HEADER": "只要跳舞僵尸开始摇滚，这些僵尸就会成对出现。",
"BALLOON_ZOMBIE_HEADER": "气球僵尸在空中飘浮，对大多数攻击免疫。",
"BEAT_IT_DESCRIPTION": "在跳舞僵尸召唤伴舞僵尸之前击败他。",
"BEAT_IT_TITLE": "击败它",
"BEEHIVE": "蜂巢",
"BEEHIVE_TOOLTIP": "生成蜜蜂，攻击任意一行",
"BETA_BUILD": "测试版：禁止传播",
"BETTER_OFF_DEAD_DESCRIPTION": "在“我是僵尸无尽版”中达到10连胜。",
"BETTER_OFF_DEAD_TITLE": "死了更好",
"BEYOND_THE_GRAVE_DESCRIPTION": "通关全部20个迷你游戏。",
"BEYOND_THE_GRAVE_TITLE": "超越坟墓",
"BLACK_FOOTBALL_ZOMBIE": "巨人橄榄球僵尸",
"BOMB_ALL_TOGETHER": "一起轰炸",
"BOSS_HEADER": "僵王博士统治一切。",
"BUCKETHEAD_ZOMBIE_HEADER": "他的铁桶帽使他极难被伤害。",
"BUNGEE_ZOMBIE_HEADER": "蹦蹦僵尸从空中发动袭击。",
"BUTTERED_POPCORN": "奶油爆米花",
"CATAPULT_ZOMBIE_HEADER": "投石车僵尸操作重型机械。",
"CHALLENGE_PAGE": "迷你游戏页",
"CHERRY_HOVER_BOMB": "樱桃悬空炸弹",
"CHERRY_HOVER_BOMB_TOOLTIP": "可以种在其他植物上方的炸弹",
"CHINA_SHOP_DESCRIPTION": "在“破罐者无尽版”中达到15连胜。",
"CHINA_SHOP_TITLE": "瓷器店",
"CONEHEAD_ZOMBIE_HEADER": "他头上的交通锥使他比普通僵尸结实两倍。",
"CONTROLLER_BUTTON": "输入控制器",
"CRAZY_DAVE_4010": "{SHAKE}奶油爆米花！{SCREAM}{MOUTH_BIG_SMILE}",
"CRAZY_DAVE_4011": "用你涂满黄油的手指触摸僵尸，把它们挡在门外！",
"CRAZY_DAVE_4012": "然后用你的玉米加农炮轰击它们！",
"CREDITS_THANKS": "感谢游玩！",
"DANCING_ZOMBIE_HEADER": "跳舞僵尸与任何在世或已故之人的相似纯属巧合。",
"DEBUG_PLAY": "（调试游玩）",
"DIGGER_ZOMBIE_HEADER": "这只僵尸挖洞绕过你的防线。",
"DISCO_IS_UNDEAD_DESCRIPTION": "催眠领舞的僵尸舞者。",
"DISCO_IS_UNDEAD_TITLE": "迪斯科永生",
"DISRESPECT_THE_DEAD_DESCRIPTION": "在单次夜间关卡中移除10座墓碑。",
"DISRESPECT_THE_DEAD_TITLE": "不敬亡灵",
"DOLPHIN_RIDER_ZOMBIE_HEADER": "海豚骑士僵尸利用海豚突破你的水池防线。",
"DONT_PEA_IN_THE_POOL_DESCRIPTION": "不使用任何豌豆射手完成一个白天的水池关卡。",
"DONT_PEA_IN_THE_POOL_TITLE": "池塘禁豆",
"DUCKY_TUBE_ZOMBIE_HEADER": "鸭子游泳圈让这只僵尸漂浮在水面上。",
"DUPLICATOR_CYCLER": "复制循环器",
"DUPLICATOR_CYCLER_TOOLTIP": "循环复制种子包",
"EVEN_MORTICULTURALIST_DESCRIPTION": "至少使用每一种植物一次。",
"EVEN_MORTICULTURALIST_TITLE": "全能植物学家",
"EXPLODONATOR_DESCRIPTION": "用一颗樱桃炸弹消灭10只成年僵尸。",
"EXPLODONATOR_TITLE": "爆破专家",
"FACE_TO_FACE_DESCRIPTION": "完成一个矿工僵尸关卡，且不让任何矿工僵尸到达草坪左侧。",
"FACE_TO_FACE_TITLE": "面对面",
"FLAG_ZOMBIE_HEADER": "旗帜僵尸标志着大批或“一波”僵尸的到来。",
"FOG_OF_WAR": "战争迷雾",
"FOOTBALL_ZOMBIE_HEADER": "橄榄球僵尸上演大戏。",
"FULLSCREEN_LABEL": "全屏",
"GAMEPLAY_SETTINGS_BUTTON": "游戏设置",
"GARGANTUAR_HEADER": "巨人僵尸是一个巨型僵尸。",
"GOLD_FARMER_DESCRIPTION": "在单次关卡中种植5株金盏花和一个吸金磁铁。",
"GOLD_FARMER_TITLE": "黄金农夫",
"GOOD_MORNING_DESCRIPTION": "只种植蘑菇和咖啡豆完成一个白天的关卡。",
"GOOD_MORNING_TITLE": "早安",
"GROUNDED_DESCRIPTION": "不使用任何投石车植物完成一个普通的屋顶关卡。",
"GROUNDED_TITLE": "脚踏实地",
"HARDWARE_LABEL": "3D加速",
"HEAT_WAVE": "热浪",
"HEAVY_WEAPON": "重武器",
"HEAVY_WEAPONS_DESCRIPTION": "仅使用玉米加农炮消灭僵尸，完成“最后一关”。",
"HEAVY_WEAPONS_TITLE": "重武器",
"HOMERUN_DERBY": "全垒打",
"HOME_LAWN_SECURITY_DESCRIPTION": "通关冒险模式。",
"HOME_LAWN_SECURITY_TITLE": "家园草坪守卫",
"ICEBERG_LETTUCE": "冰叶生菜",
"ICEBERG_LETTUCE_TOOLTIP": "投掷冰冷的生菜叶，减缓敌人速度",
"IMMORTAL_DESCRIPTION": "在纯僵尸狂暴中生存20波。",
"IMMORTAL_TITLE": "不朽",
"IMP_HEADER": "小鬼僵尸是被巨人僵尸抛向防线深处的微型僵尸。",
"JACK_IN_THE_BOX_ZOMBIE_HEADER": "这只僵尸携带着爆炸惊喜。",
"LADDER_ZOMBIE_HEADER": "扶梯僵尸爬过障碍物。",
"LANGUAGE_BUTTON": "语言",
"LAST_STAND_DAY": "最后一关：白天",
"LAST_STAND_DAY_ENDLESS": "最后一关：白天（无尽版）",
"LAST_STAND_FOG": "最后一关：迷雾",
"LAST_STAND_FOG_ENDLESS": "最后一关：迷雾（无尽版）",
"LAST_STAND_NIGHT": "最后一关：夜晚",
"LAST_STAND_NIGHT_ENDLESS": "最后一关：夜晚（无尽版）",
"LAST_STAND_PAGE": "最后一关页",
"LAST_STAND_POOL": "最后一关：水池",
"LAST_STAND_POOL_ENDLESS": "最后一关：水池（无尽版）",
"LAST_STAND_ROOF": "最后一关：屋顶",
"LAST_STAND_ROOF_ENDLESS": "最后一关：屋顶（无尽版）",
"LIMBO": "炼狱",
"LIMBO_PAGE": "炼狱页",
"LOADING_LINES": "加载中...",
"MAY_NOT_CONTAIN_NUTS_DESCRIPTION": "不使用坚果墙或高坚果完成一个夜晚关卡。",
"MAY_NOT_CONTAIN_NUTS_TITLE": "可能不含坚果",
"MORTICULTURALIST_DESCRIPTION": "收集全部49种植物（包括疯狂戴夫商店里的植物）。",
"MORTICULTURALIST_TITLE": "植物学家",
"MUSIC_LABEL": "音乐",
"MUSTACHE_MODE_DESCRIPTION": "开启“胡子模式”。",
"MUSTACHE_MODE_TITLE": "胡子模式",
"NEWSPAPER_ZOMBIE_HEADER": "他的报纸提供了有限的防御。",
"NOBEL_PEAS_PRIZE_DESCRIPTION": "获得金色的向日葵奖杯。",
"NOBEL_PEAS_PRIZE_TITLE": "豌豆诺贝尔奖",
"NOT_SUPPORTED_HEADER": "不受支持",
"NOT_SUPPORTED_LINES": "此电脑无法启用硬件加速。你的显卡不满足本游戏的最低要求。",
"NO_FUNGUS_AMONG_US_DESCRIPTION": "不种植任何蘑菇完成一个夜晚关卡。",
"NO_FUNGUS_AMONG_US_TITLE": "我们中间没有蘑菇",
"NO_WINDOWED_HEADER": "无法窗口化",
"NO_WINDOWED_LINES": "只有在你启动游戏时桌面为16位或32位颜色模式，才能使用窗口模式。若想使用窗口模式，请退出游戏并将桌面切换为16或32位颜色模式。",
"NUKECUMBER": "核瓜",
"NUKECUMBER_TOOLTIP": "核平整个棋盘，留下一片焦土",
"OK_LABEL": "确定",
"ONE_MORE_LAST_STAND_TOOLTIP": "再获得1个“最后一关”奖杯即可解锁",
"OPTIONS": "选项",
"PENNY_PINCHER_DESCRIPTION": "在单次关卡中连续拾取30枚金币，且不让任何一枚消失。",
"PENNY_PINCHER_TITLE": "守财奴",
"POGO_ZOMBIE_HEADER": "弹簧僵尸跳跃前进，绕过你的防线。",
"POLE_VAULTING_ZOMBIE_HEADER": "撑杆僵尸借助撑杆越过障碍。",
"POPCORN_PARTY_DESCRIPTION": "用玉米加农炮导弹在单次关卡中消灭2只巨人僵尸。",
"POPCORN_PARTY_TITLE": "爆米花派对",
"PREVIEW_BUILD": "媒体/合作伙伴预览版：禁止传播",
"PUZZLE_PAGE": "益智模式页",
"QUICKPLAY": "快速游戏",
"ROLL_SOME_HEADS_DESCRIPTION": "用一个坚果墙碾压5只僵尸。",
"ROLL_SOME_HEADS_TITLE": "碾压脑袋",
"SCORE_LABEL": "得分",
"SCREEN_DOOR_ZOMBIE_HEADER": "他的铁门是有效的护盾。",
"SELECT_LANGUAGE": "选择语言",
"SHOUT_LABEL": "大声喊！",
"SKIP_CUTSCENE_BUTTON": "跳过过场动画",
"SNORKEL_ZOMBIE_HEADER": "潜水僵尸可以在水下游泳。",
"SOUND_LABEL": "音效",
"SPUDOW_DESCRIPTION": "用土豆雷炸飞一只僵尸。",
"SPUDOW_TITLE": "土豆爆炸！",
"STINGER": "蜂刺射手",
"STINGER_TOOLTIP": "向飞行僵尸发射尖刺",
"SULTAN_OF_SPIN_DESCRIPTION": "在“旋转宝石迷阵”中升级你的所有植物。",
"SULTAN_OF_SPIN_TITLE": "旋转苏丹",
"SUNNY_DAYS_DESCRIPTION": "在单次关卡中获得8000点阳光。",
"SUNNY_DAYS_TITLE": "阳光明媚的日子",
"SURVIVAL_HIGHGROUND_ENDLESS": "生存模式：高地（无尽版）",
"SURVIVAL_HIGHGROUND_HARD": "生存模式：高地（困难版）",
"SURVIVAL_HIGHGROUND_NORMAL": "生存模式：高地",
"SURVIVAL_NIGHTROOF_ENDLESS": "生存模式：夜间屋顶（无尽版）",
"SURVIVAL_NIGHTROOF_HARD": "生存模式：夜间屋顶（困难版）",
"SURVIVAL_NIGHTROOF_NORMAL": "生存模式：夜间屋顶",
"SURVIVAL_PAGE": "生存模式页",
"TIME_STOPPER": "时间停止器",
"TIME_STOPPER_TOOLTIP": "立即为你的其他种子补充能量",
"TOWERING_WISDOM_DESCRIPTION": "将智慧之树培育到100英尺。",
"TOWERING_WISDOM_TITLE": "高耸的智慧",
"TRASHCAN_ZOMBIE": "垃圾桶僵尸",
"TRASHCAN_ZOMBIE_DESCRIPTION": "垃圾桶僵尸说明",
"UNLOCK_DIALOG_BODY": "你确定要解锁全部游戏内容吗？",
"UNLOCK_DIALOG_HEADER": "解锁完整游戏",
"VASE_BREAKER": "破罐者",
"WARNING_HEADER": "警告",
"WARNING_LINES": "你的显卡可能无法完全支持此功能。如果遇到性能下降，请禁用硬件加速。",
"WINDOW_DEBUG": "调试",
"WINDOW_TITLE": "植物大战僵尸",
"YAMPOLINE": "山药蹦床",
"YAMPOLINE_TOOLTIP": "把僵尸弹离旁边的植物",
"ZEN_PROFIT_DESCRIPTION": "通过你的休闲花园累计赚取100,000枚硬币。",
"ZEN_PROFIT_TITLE": "花园收益",
"ZOMBIE_BOBSLED_TEAM_HEADER": "这些僵尸以四人小队的形式出现。",
"ZOMBIE_HEADER": "普通的花园品种僵尸",
"ZOMBIE_TRAP": "僵尸陷阱",
"ZOMBIE_YETI_HEADER": "一种稀有而神秘的生灵。",
"ZOMBOLOGIST_DESCRIPTION": "发现雪人僵尸。",
"ZOMBOLOGIST_TITLE": "僵尸学家",
"ZOMBONI_HEADER": "冰车僵尸对你的植物施加冰、蒸汽与压力。",
}

# 校验：必须是全部 174 个（与英文 extra 一一对应）
import re
def parse_lawnstrings(path, enc):
    text = io.open(path,'r',encoding=enc,errors='replace').read()
    d = {}
    for m in re.finditer(r'\[([^\]]+)\][ \t]*\r?\n(.*?)(?=\r?\n\[|\Z)', text, re.DOTALL):
        d[m.group(1).strip().upper()] = re.sub(r'\r?\n','',m.group(2).strip())
    return d
en = parse_lawnstrings(r'C:\Users\Administrator\Documents\GitHub\stabledecompile\_tools\dep_pak\dependency\properties\LawnStrings.txt','latin-1')
cn = parse_lawnstrings(r'C:\Users\Administrator\Documents\GitHub\stabledecompile\_tools\cn_pak\properties\LawnStrings.txt','utf-16')
extra = sorted(set(en)-set(cn))
missing = [k for k in extra if k not in TRANS]
print("extra count:", len(extra), " translated count:", len(TRANS), " missing:", missing)

# 写入 UTF-8 无 BOM 的补充文件
out = r'C:\Users\Administrator\Documents\GitHub\stabledecompile\_tools\dep_pak_full\dependency\properties\LawnStrings.txt'
lines=[]
for k in extra:
    lines.append("[%s]\n%s\n\n" % (k, TRANS[k]))
data = "".join(lines).encode('utf-8')
with open(out,'wb') as f:
    f.write(data)
print("wrote", out, len(data), "bytes")
# 校验 BOM
with open(out,'rb') as f:
    head=f.read(3)
print("BOM check (should not start EF BB BF):", head.hex())
